### ISSUE TITLE
适配移动端

### ISSUE THREAD

**Issue by HimekoX** [newcdn/bilibili#6]
移动端播放打开没有看到发送弹幕选项  另外广告设置需要演示 图片广告设置一直未生效

**Comment by freecreditcc** [comment]
https://dramaking.tv/player/?url=https://cdn-yong.bejingyongjiu.com/20210102/29655_c57cba6c/index.m3u8

你说的这2个问题，我都没有问题
唯独只有暂停广告有效

**Comment by HimekoX** [comment]
qq内打开播放器被劫持了 暂停广告有效  但是全屏下就不显示 片头广告无法显示 不知道是不是我加了cdn的原因 
https://player.pixiv.love/player/?url=https://database.iloli.life/t/PaPe9S
另外再贴出一个我买的别人二改的项目大佬可以看看
https://github.com/HimekoX/bilibili-player
